post_install() {
     usr/sbin/mateconfpkg --install mate-conf-editor
     gtk-update-icon-cache -q -t -f usr/share/icons/hicolor
     update-desktop-database -q
}

pre_upgrade() {
    pre_remove $1
}

post_upgrade() {
    post_install $1
}

pre_remove() {
    usr/sbin/mateconfpkg --uninstall mate-conf-editor
}

post_remove() {
    gtk-update-icon-cache -q -t -f usr/share/icons/hicolor
    update-desktop-database -q
}

